#!/usr/bin/env bash

set -euxo pipefail

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Hostname / flake URI to install. matches base name of the file
HOSTNAME="$1"
shift

DEVICE="$1"
shift

ARGS=()
while [ "$#" -gt 0 ]; do
    i="$1"; shift 1
    case "$i" in
        --debug)
            set -x
            ;;
       *)
            ARGS+=($i)
            ;;
    esac
done

nix() {
  command nix "$@"
}

just nixos-rebuild build ".#$HOSTNAME" && \
  find ./result/iso -name '*.iso' | xargs -I {} dd if={} of="$DEVICE" bs=64M
