#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

VERB="$1"
shift

TARGET="$1"
shift

ARGS=(
  --rm
  -v "$FLAKE_ROOT:/workdir"
)

PLATFORM_ARGS=()
if [[ -n "${PLATFORM:-}" ]]; then
  PLATFORM_ARGS+=(--platform "$PLATFORM")
fi

env --chdir "$SCRIPTPATH" \
    nix shell nixpkgs#docker --command \
      docker build "${PLATFORM_ARGS[@]}" -t nix-docker . \
      && docker run "${PLATFORM_ARGS[@]}" "${ARGS[@]}" -it nix-docker
