#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

VERB="$1"
shift

TARGET="$1"
shift

ARGS=(
  --rm
  -v "$FLAKE_ROOT:/workdir"
)

PLATFORM_ARGS=()
if [[ -n "${PLATFORM:-}" ]]; then
  PLATFORM_ARGS+=(--platform "$PLATFORM")
fi

[[ "${VERBOSE:-0}" -eq 1 ]] && ARGS+=(-e VERBOSE=1)
[[ "${DEBUG:-0}" -eq 1 ]] && ARGS+=(-e DEBUG=1)

env --chdir "$SCRIPTPATH" \
    nix shell nixpkgs#docker --command \
      docker build "${PLATFORM_ARGS[@]}" -t nix-docker . \
      && docker run "${PLATFORM_ARGS[@]}" "${ARGS[@]}" -it nix-docker \
        nix run nixpkgs#just -- run "$VERB" "$TARGET" "$@"
