#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

# Platform to install.
HOSTNAME="$1"
shift

# Device to install to.
DEVICE="$1"
shift

# If a custom override handler exists, call that.
HOSTNAME_OVERRIDE="$SCRIPTPATH/$HOSTNAME/runner"
if [[ -f "$HOSTNAME_OVERRIDE" ]]; then
	command "$SCRIPTPATH/exec-in-tmpfs" "$HOSTNAME_OVERRIDE" "$HOSTNAME" "$DEVICE" "$@"
else
	echo "Don't know how to install ${HOSTNAME@Q}."
fi
