#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

ARGS=(
)

VERB="$1"
shift

case "$VERB" in
  show|check)
    nix flake "$VERB" "${ARGS[@]}" "$@"
    ;;
  *)
	# todo strip out flake refs here
    nix develop --command nix "$VERB" "${ARGS[@]}" "$@"
    ;;
esac
