#!/usr/bin/env bash

ARGS=(
)

VERB="$1"
shift

nix() {
  command nix --extra-experimental-features 'nix-command flakes' --inputs-from "$FLAKE_ROOT" "$@"
}

case "$VERB" in
  show|check)
    nix flake "$VERB" "${ARGS[@]}" "$@"
    ;;
  *)
	# todo strip out flake refs here
    nix develop --command nix --extra-experimental-features 'nix-command flakes'  "$VERB" "${ARGS[@]}" "$@"
    ;;
esac
