#!/usr/bin/env bash

ARGS=(
)

VERB="$1"
shift

case "$VERB" in
  show|check)
    nix flake "$VERB" "${ARGS[@]}" "$@"
    ;;
  *)
	# todo strip out flake refs here
    nix develop --command nix "$VERB" "${ARGS[@]}" "$@"
    ;;
esac
