#!/usr/bin/env bash

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

mkOverlayDirs() {
  tmp="$(mktemp -d)"
  mkdir -p "$tmp/.ro"
  mkdir -p "$tmp/.rw/upper"
  mkdir -p "$tmp/.rw/work"
  echo "$tmp"
}

mountOverlay() {
  tmp="$(mkOverlayDirs)"

  finish() {
    umount -f "$tmp"
    umount -f "$tmp/.ro"
    rm -r "$tmp"
  }

  trap finish EXIT

  mount -B "$(realpath "$1")" "$tmp/.ro"
  mount -t overlay overlay -o "lowerdir=$tmp/.ro,upperdir=$tmp/.rw/upper,workdir=$tmp/.rw/work" "$tmp"
}

for d in "$@"; do
  mountOverlay "$d"
done
