# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod"];
      kernelModules = ["amdgpu"];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };
  networking.useDHCP = lib.mkDefault true;

  networking.interfaces.enp10s0 = {
    useDHCP = false;
    ipv4.addresses = [
      {
        address = "169.254.199.18";
        prefixLength = 16;
      }
    ];
    macAddress = "c8:7f:54:6a:6e:4b";
    wakeOnLan = {
      enable = true;
      policy = [
        "broadcast"
        "magic"
      ];
    };
  };

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
