#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

ARGS=(
  --use-remote-sudo
  --flake "$FLAKE_ROOT"
)

"$SCRIPTPATH/nixos-rebuild" "${ARGS[@]}" "$@"
