#!/usr/bin/env bash

set -euxo pipefail

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Hostname / flake URI to install. matches base name of the file
HOSTNAME="$1"
shift

DEVICE="$1"
shift

TRACE=0
ARGS=()
while [ "$#" -gt 0 ]; do
    i="$1"; shift 1
    case "$i" in
        --debug)
            set -x
            TRACE=1
            ;;
       *)
            ARGS+=($i)
            ;;
    esac
done

nix() {
  command nix "$@"
}

if [[ "$TRACE" -eq 1 ]]; then
  MACHINE="$HOSTNAME" nix run github:nix-community/disko\#disko-install -- --show-trace --write-efi-boot-entries \
    --flake "$FLAKE_ROOT#$HOSTNAME" --disk main "$DEVICE" "$@"
else
  MACHINE="$HOSTNAME" nix run github:nix-community/disko\#disko-install -- --write-efi-boot-entries \
    --flake "$FLAKE_ROOT#$HOSTNAME" --disk main "$DEVICE" "$@"
fi
